{!!python/unicode 'bio': null, !!python/unicode 'email_address': null, !!python/unicode 'gold_medals': 0,
  !!python/unicode 'id': 3, !!python/unicode 'reputation': 0, !!python/unicode 'user_name': !!python/unicode 'zxc'}
